version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file inputSmarRrouterCF.yaml --s3-bucket smart-router --output-template-file outputSmarRrouterCF.yaml
artifacts:
  type: zip
  files:
    - inputSmarRrouterCF.yaml
    - outputSmarRrouterCF.yaml
